---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: GitHub
    mappingMethod: claim
    type: GitHub
    github:
      clientID: <this stupid value is hardcoded FIXME>
      clientSecret:
        name: github-oauth
      organizations:
      - dwnwrd
  - name: HTPasswd
    mappingMethod: claim
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpasswd
