# Oauth base to setup htpasswd auth
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- oauth.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: htpasswd
  namespace: openshift-config
  files:
    - htpasswd

# in overlays per cluster
#- name: github-oauth
#  namespace: openshift-config
#  files:
#    - clientSecret
#- name: github-oauth-client-id
#  namespace: openshift-config
#  files:
#    - clientId
