# ClusterDeployment base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: aws-creds
    envs:
      - .env.aws

  - name: azure-creds
    files:
      - osServicePrincipal.json

  - name: pull-secret
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson

  - name: ssh-private-key
    files:
      - ssh-privatekey

  - name: vsphere-creds
    envs:
      - .env.vsphere

  - name: vsphere-certs
    files:
      - .cacert

resources:
- klusterletaddonconfig.yaml
- clusterdeployment.yaml
- machinepool.yaml
- managedcluster.yaml
