apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sno1
commonLabels:
  hive.openshift.io/cluster-deployment-name: sno1

bases:
  - ../../../../kustomize/clusterdeploy

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: install-config
    files:
    - install-config.yaml

resources:
  - namespace.yaml

patchesStrategicMerge:
  - patches/klusterletaddonconfig.yaml
  - patches/machinepool.yaml
  - patches/clusterdeployment.yaml
  - patches/managedcluster.yaml

patches:
  - target:
      kind: ClusterDeployment
      name: tbd
    patch: |-
      - op: replace
        path: /metadata/name
        value: sno1

  - target:
      kind: ManagedCluster
      name: tbd
    patch: |-
      - op: replace
        path: /metadata/name
        value: sno1

  - target:
      kind: KlusterletAddonConfig
      name: tbd
    patch: |-
      - op: replace
        path: /metadata/name
        value: sno1

